/**
 * List of countries supported for Stripe Connect account creation.
 */
export const countries = [
    { label: "Australia", code: "AU" },
    { label: "Austria", code: "AT" },
    { label: "Belgium", code: "BE" },
    { label: "Bulgaria", code: "BG" },
    { label: "Canada", code: "CA" },
    { label: "Croatia", code: "HR" },
    { label: "Cyprus", code: "CY" },
    { label: "Czech Republic", code: "CZ" },
    { label: "Denmark", code: "DK" },
    { label: "Estonia", code: "EE" },
    { label: "Finland", code: "FI" },
    { label: "France", code: "FR" },
    { label: "Germany", code: "DE" },
    { label: "Gibraltar", code: "GI" },
    { label: "Greece", code: "GR" },
    { label: "Hong Kong SAR China", code: "HK" },
    { label: "Hungary", code: "HU" },
    { label: "Ireland", code: "IE" },
    { label: "Italy", code: "IT" },
    { label: "Japan", code: "JP" },
    { label: "Latvia", code: "LV" },
    { label: "Liechtenstein", code: "LI" },
    { label: "Lithuania", code: "LT" },
    { label: "Luxembourg", code: "LU" },
    { label: "Malta", code: "MT" },
    { label: "Mexico", code: "MX" },
    { label: "Netherlands", code: "NL" },
    { label: "New Zealand", code: "NZ" },
    { label: "Norway", code: "NO" },
    { label: "Poland", code: "PL" },
    { label: "Portugal", code: "PT" },
    { label: "Romania", code: "RO" },
    { label: "Singapore", code: "SG" },
    { label: "Slovakia", code: "SK" },
    { label: "Slovenia", code: "SI" },
    { label: "Spain", code: "ES" },
    { label: "Sweden", code: "SE" },
    { label: "Switzerland", code: "CH" },
    { label: "Thailand", code: "TH" },
    { label: "United Arab Emirates", code: "AE" },
    { label: "United Kingdom", code: "GB" },
    { label: "United States", code: "US" },
];
